export type EmailField = {
  label: string;
  value?: string | number | null;
};

export type BrandedEmailOptions = {
  preview: string;
  eyebrow: string;
  title: string;
  intro: string;
  fields?: EmailField[];
  message?: string;
  footerNote?: string;
};

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function formatText(value?: string | number | null) {
  if (value === undefined || value === null || value === "") {
    return "Not provided";
  }

  return escapeHtml(String(value));
}

function renderFieldRows(fields: EmailField[] = []) {
  if (fields.length === 0) {
    return "";
  }

  return fields
    .map(
      (field) => `
        <tr>
          <td style="padding:14px 0;border-bottom:1px solid #e5edf6;color:#64748b;font-size:13px;line-height:20px;width:38%;">${escapeHtml(field.label)}</td>
          <td style="padding:14px 0;border-bottom:1px solid #e5edf6;color:#0f2747;font-size:14px;line-height:22px;font-weight:600;">${formatText(field.value)}</td>
        </tr>`
    )
    .join("");
}

export function renderAulexmedEmail({
  preview,
  eyebrow,
  title,
  intro,
  fields = [],
  message,
  footerNote = "AULEXMED transactional email. This message was generated by the official AULEXMED website system."
}: BrandedEmailOptions) {
  const safeMessage = message
    ? `<div style="margin-top:24px;padding:18px 20px;border-radius:18px;background:#f8fbff;border:1px solid #e5edf6;color:#19385f;font-size:14px;line-height:24px;white-space:pre-wrap;">${escapeHtml(message)}</div>`
    : "";

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${escapeHtml(title)}</title>
    <meta name="description" content="${escapeHtml(preview)}">
  </head>
  <body style="margin:0;background:#eef5fb;padding:0;font-family:Arial,Helvetica,sans-serif;color:#0f2747;">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">${escapeHtml(preview)}</div>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef5fb;margin:0;padding:32px 16px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#ffffff;border-radius:24px;overflow:hidden;border:1px solid #dce8f4;box-shadow:0 18px 45px rgba(15,39,71,0.08);">
            <tr>
              <td style="padding:34px 34px 22px;background:linear-gradient(135deg,#f7fbff 0%,#ffffff 58%,#eaf4ff 100%);">
                <div style="font-size:12px;letter-spacing:0.16em;text-transform:uppercase;color:#2f7fd3;font-weight:700;">AULEXMED</div>
                <div style="margin-top:16px;font-size:12px;letter-spacing:0.14em;text-transform:uppercase;color:#7a8da6;font-weight:700;">${escapeHtml(eyebrow)}</div>
                <h1 style="margin:10px 0 0;color:#0f2747;font-size:30px;line-height:38px;font-weight:700;letter-spacing:0;">${escapeHtml(title)}</h1>
                <p style="margin:16px 0 0;color:#4f6682;font-size:15px;line-height:25px;">${escapeHtml(intro)}</p>
              </td>
            </tr>
            <tr>
              <td style="padding:8px 34px 34px;">
                <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
                  ${renderFieldRows(fields)}
                </table>
                ${safeMessage}
              </td>
            </tr>
            <tr>
              <td style="padding:24px 34px;background:#0f2747;color:#dbeafe;">
                <p style="margin:0;font-size:13px;line-height:21px;">Back to Life. One Step at a Time.</p>
                <p style="margin:8px 0 0;font-size:12px;line-height:20px;color:#a9c1dd;">${escapeHtml(footerNote)}</p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

export function supportRequestTemplate(fields: EmailField[], message?: string) {
  return renderAulexmedEmail({
    preview: "New AULEXMED support request received.",
    eyebrow: "Support Request",
    title: "New Customer Support Request",
    intro: "A customer submitted a support request through an AULEXMED website or system channel.",
    fields,
    message
  });
}

export function b2bInquiryTemplate(fields: EmailField[], message?: string) {
  return renderAulexmedEmail({
    preview: "New AULEXMED B2B inquiry received.",
    eyebrow: "B2B Inquiry",
    title: "New Partnership Inquiry",
    intro: "A potential partner is asking about wholesale, distributor, OEM, ODM, or manufacturing cooperation.",
    fields,
    message
  });
}

export function quoteRequestTemplate(fields: EmailField[], message?: string) {
  return renderAulexmedEmail({
    preview: "New AULEXMED quote request received.",
    eyebrow: "Quote Request",
    title: "New Product Quotation Request",
    intro: "A buyer requested pricing or quotation information for AULEXMED orthopedic support products.",
    fields,
    message
  });
}

export function generalContactTemplate(fields: EmailField[], message?: string) {
  return renderAulexmedEmail({
    preview: "New AULEXMED contact message received.",
    eyebrow: "General Contact",
    title: "New Website Contact Message",
    intro: "A website visitor submitted a general contact message for the AULEXMED team.",
    fields,
    message
  });
}

export function chatbotEscalationTemplate(fields: EmailField[], message?: string) {
  return renderAulexmedEmail({
    preview: "AULEXMED AI assistant escalated a conversation.",
    eyebrow: "Chatbot Escalation",
    title: "AI Assistant Follow-up Needed",
    intro: "The AULEXMED AI assistant identified a conversation that may need human review or follow-up.",
    fields,
    message
  });
}

export function autoReplyTemplate(fields: EmailField[], message?: string) {
  return renderAulexmedEmail({
    preview: "AULEXMED has received your message.",
    eyebrow: "Auto Reply",
    title: "We Received Your Message",
    intro: "Thank you for contacting AULEXMED. Our team will review your message and respond through the appropriate support or business channel.",
    fields,
    message,
    footerNote: "This is an automatic confirmation from AULEXMED. Please do not reply with urgent medical questions; consult a healthcare professional for medical advice."
  });
}
